name: no_delala
description: Home services employment app
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # navigation
  go_router: ^14.2.0

  # networking
  dio: ^5.4.3
  socket_io_client: ^2.0.3+1

  # local storage
  flutter_secure_storage: ^9.2.2

  # media
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1

  # env
  flutter_dotenv: ^5.1.0

  # notifications
  flutter_local_notifications: ^17.2.1

  # utilities
  intl: ^0.19.0               # date formatting in chat
  equatable: ^2.0.5           # model equality checks

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9        # for riverpod code gen
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600